[codestyle]
workspace_dir='~/git/github.com/anosillus/procon/atcoder'
lang='nim'
template_file='~/dotfiles/vim/template/procon/template.nim'
[tester]
compile_before_testing=true
compile_only_when_diff_detected=true
[etc]
download_without_login=true
parallel_download=false
save_no_session_cache=false
