yaskkserv2 --config-filename /home/anosillus/.skk/linux_yaskkserv2.conf

# [[ -f ~/.screenlayout/home.sh ]] && . ~/.screenlayout/home.sh

#xrandr --output DP-4 --auto --left-of DP-2 --rotate right
# sudo -u xkeysnail DISPLAY=$DISPLAY /usr/sbin/xkeysnail --watch --quiet $HOME/.config/xkeysnail/config.py

export GTK_IM_MODULE=fcitx
export QT_IM_MODULE=fcitx
export XMODIFIERS=@im=fcitx
export GLFW_IM_MODULE=ibus
# ibus-daemon --daemonize --xim
Xim=`which fcitx5`
XimArgs="-r -d"
[ -x $Xim ] && $Xim $XimArgs &
fcitx5 -r -d &

[[ -f ~/.bashrc ]] && . ~/.bashrc

export PATH="/usr/local/bin:$HOME/bin:$PATH"
export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
# export PYTHONPATH=/usr/bin/python3
export LC_ALL=en_US.UTF-8,
export LANG=en_US.UTF-8,
export LANGUAGE="",
export LC_ALL=""
export LC_ADDRESS="ja_JP.UTF-8",
export LC_NAME="ja_JP.UTF-8",
export LC_MONETARY="ja_JP.UTF-8",
export LC_PAPER="ja_JP.UTF-8",
export LC_IDENTIFICATION="ja_JP.UTF-8",
export LC_TELEPHONE="ja_JP.UTF-8",
export LC_MEASUREMENT="ja_JP.UTF-8",
export LC_TIME="ja_JP.UTF-8",
export LC_NUMERIC="ja_JP.UTF-8",
export LANG="en_US",
export LC_ALL="C"

# eval "$(pyenv virtualenv-init -)"

#source /home/anosillus/.config/broot/launcher/bash/br

export PATH="$HOME/.poetry/bin:$PATH"
. "$HOME/.cargo/env"
