if [ -f ~/.bashrc ]; then
  source ~/.bashrc
fi
export PATH="/usr/local/bin:$HOME/bin:$PATH"

export PATH="$HOME/.poetry/bin:$PATH"

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/tyda/Downloads/google-cloud-sdk/path.bash.inc' ]; then . '/Users/tyda/Downloads/google-cloud-sdk/path.bash.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/tyda/Downloads/google-cloud-sdk/completion.bash.inc' ]; then . '/Users/tyda/Downloads/google-cloud-sdk/completion.bash.inc'; fi

export PATH="$HOME/.cargo/bin:$PATH"

export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
export GTK_IM_MODULE=ibus
export XMODIFIRES=@im=ibus
export QT_IM_MODULE=ibus
