ln -s /home/anosillus/.atcodertools.toml /home/anosillus/dotfiles/dots/atcodertools.toml
ln -s /home/anosillus/.auto-start /home/anosillus/dotfiles/dots/auto-start
ln -s /home/anosillus/.bash_profile /home/anosillus/dotfiles/dots/bash_profile
ln -s /home/anosillus/.gitconfig /home/anosillus/dotfiles/dots/gitconfig
ln -s /home/anosillus/.gvimrc /home/anosillus/dotfiles/dots/gvimrc
ln -s /home/anosillus/.kaggle /home/anosillus/dotfiles/dots/kaggle
ln -s /home/anosillus/.signate /home/anosillus/dotfiles/dots/signate
ln -s /home/anosillus/.textlintrc /home/anosillus/dotfiles/dots/textlintrc
ln -s /home/anosillus/.tmux.conf /home/anosillus/dotfiles/dots/tmux.conf
ln -s /home/anosillus/.vim /home/anosillus/dotfiles/dots/vim
ln -s /home/anosillus/.vimrc /home/anosillus/dotfiles/dots/vimrc
ln -s /home/anosillus/.yaskkserv2 /home/anosillus/dotfiles/dots/yaskkserv2
ln -s /home/anosillus/.skk /home/anosillus/dotfiles/dots/skk

ln -s /home/anosillus/.config/alacritty /home/anosillus/dotfiles/dots/config/alacritty
ln -s /home/anosillus/.config/albert /home/anosillus/dotfiles/dots/config/albert
ln -s /home/anosillus/.config/barabiner /home/anosillus/dotfiles/dots/config/barabiner
ln -s /home/anosillus/.config/brewfile /home/anosillus/dotfiles/dots/config/brewfile
ln -s /home/anosillus/.config/coc /home/anosillus/dotfiles/dots/config/coc
ln -s /home/anosillus/.config/efm-langserver /home/anosillus/dotfiles/dots/config/efm-langserver
ln -s /home/anosillus/.config/fish /home/anosillus/dotfiles/dots/config/fish
ln -s /home/anosillus/.config/git /home/anosillus/dotfiles/dots/config/git
ln -s /home/anosillus/.config/i3 /home/anosillus/dotfiles/dots/config/i3
ln -s /home/anosillus/.config/nvim /home/anosillus/dotfiles/dots/config/nvim
ln -s /home/anosillus/.config/pip /home/anosillus/dotfiles/dots/config/pip
ln -s /home/anosillus/.config/polybar /home/anosillus/dotfiles/dots/config/polybar
ln -s /home/anosillus/.config/rofi /home/anosillus/dotfiles/dots/config/rofi
ln -s /home/anosillus/.config/scoop /home/anosillus/dotfiles/dots/config/scoop
