ln -s /home/anosillus/dotfiles/dots/atcodertools.toml /home/anosillus/.atcodertools.toml
ln -s /home/anosillus/dotfiles/dots/auto-start /home/anosillus/.auto-start
ln -s /home/anosillus/dotfiles/dots/bash_profile /home/anosillus/.bash_profile
ln -s /home/anosillus/dotfiles/dots/gitconfig /home/anosillus/.gitconfig
ln -s /home/anosillus/dotfiles/dots/gvimrc /home/anosillus/.gvimrc
ln -s /home/anosillus/dotfiles/dots/kaggle /home/anosillus/.kaggle
ln -s /home/anosillus/dotfiles/dots/signate /home/anosillus/.signate
ln -s /home/anosillus/dotfiles/dots/textlintrc /home/anosillus/.textlintrc
ln -s /home/anosillus/dotfiles/dots/tmux.conf /home/anosillus/.tmux.conf
ln -s /home/anosillus/dotfiles/dots/vim /home/anosillus/.vim
ln -s /home/anosillus/dotfiles/dots/vimrc /home/anosillus/.vimrc
ln -s /home/anosillus/dotfiles/dots/yaskkserv2 /home/anosillus/.yaskkserv2
ln -s /home/anosillus/dotfiles/dots/skk /home/anosillus/.skk

ln -s /home/anosillus/dotfiles/dots/config/alacritty /home/anosillus/.config/alacritty
ln -s /home/anosillus/dotfiles/dots/config/albert /home/anosillus/.config/albert
ln -s /home/anosillus/dotfiles/dots/config/karabiner /home/anosillus/.config/karabiner
ln -s /home/anosillus/dotfiles/dots/config/brewfile /home/anosillus/.config/brewfile
ln -s /home/anosillus/dotfiles/dots/config/coc /home/anosillus/.config/coc
ln -s /home/anosillus/dotfiles/dots/config/efm-langserver /home/anosillus/.config/efm-langserver
ln -s /home/anosillus/dotfiles/dots/config/fish /home/anosillus/.config/fish
ln -s /home/anosillus/dotfiles/dots/config/git /home/anosillus/.config/git
ln -s /home/anosillus/dotfiles/dots/config/i3 /home/anosillus/.config/i3
ln -s /home/anosillus/dotfiles/dots/config/nvim /home/anosillus/.config/nvim
ln -s /home/anosillus/dotfiles/dots/config/pip /home/anosillus/.config/pip
ln -s /home/anosillus/dotfiles/dots/config/polybar /home/anosillus/.config/polybar
ln -s /home/anosillus/dotfiles/dots/config/rofi /home/anosillus/.config/rofi
ln -s /home/anosillus/dotfiles/dots/config/scoop /home/anosillus/.config/scoop
