hook_add = '''
" Python
let g:python_highlight_all = 1
" Vim
let g:vimsyntax_noerror = 1
" Bash
let g:is_bash = 1
" JavaScript
let g:SimpleJsIndenter_BriefMode = 1
let g:SimpleJsIndenter_CaseIndentLevel = -1
" Tex
let g:tex_flavor = 'latex'
let g:sql_type_default = 'pgsql'
let g:go_bin_path = $GOPATH.'/bin'
" http://mattn.kaoriya.net/software/vim/20140523124903.htm
" Markdown
let g:markdown_fenced_languages = [
      \  'python',
      \  'rust',
      \  'Dockerfile',
      \  'coffee',
      \  'css',
      \  'erb=eruby',
      \  'javascript',
      \  'js=javascript',
      \  'c++=cpp',
      \  'viml=vim',
      \  'bash=sh',
      \  'ini=dosini',
      \  'json=javascript',
      \  'ruby',
      \  'sass',
      \  'xml',
      \]
" Folding
let g:tex_fold_enabled = 1
let g:xml_syntax_folding = 1
let g:php_folding = 1
let g:perl_fold = 1

" Update filetype.
autocmd MyAutoCmd BufWritePost * nested
\ if &l:filetype ==# '' || exists('b:ftdetect')
\ |   unlet! b:ftdetect
\ |   filetype detect
\ | endif

" Auto reload VimScript.
autocmd MyAutoCmd BufWritePost,FileWritePost *.vim nested
\ if &l:autoread > 0 | source <afile> |
\   echo 'source ' . bufname('%') |
\ endif
'''

[ftplugin]

_ = '''
  " Disable automatically insert comment.
  setl formatoptions-=r
  setl formatoptions-=o
  setl formatoptions+=mMBl
  " Disable auto wrap.
  if &l:textwidth != 70 && &filetype !=# 'help'
    setlocal textwidth=0
  endif
  if !&l:modifiable
    setlocal nofoldenable
    setlocal foldcolumn=0
    setlocal colorcolumn=
  endif
'''

python = '''
" Indent settings.
setlocal softtabstop=4
setlocal shiftwidth=4
setlocal textwidth=88
setlocal smarttab
setlocal expandtab
setlocal nosmartindent
'''

html = '''
setlocal keywordprg=:DD
setlocal includeexpr=substitute(v:fname,'^\\/','','')
setlocal path+=./;/
'''

go = '''
highlight default link goErr WarningMsg
match goErr /\<err\>/
'''

vim = '''
if line('$') > 1000
  syntax sync minlines=200
endif
setlocal foldmethod=marker
setlocal shiftwidth=2 softtabstop=2
setlocal iskeyword+=:,#
'''

qfreplace = 'setlocal nofoldenable'

help = '''
setlocal iskeyword+=:
setlocal iskeyword+=#
setlocal iskeyword+=-
'''

json = '''
setlocal expandtab foldmarker=syntax
'''

javascript = '''
setlocal keywordprg=:DD
setlocal foldmethod=syntax
'''

fish = '''
compiler fish
setlocal textwidth=79
setlocal foldmethod=expr
'''

ruby = '''
setlocal iskeyword+=!
setlocal iskeyword+=?
setlocal omnifunc=
setlocal shiftwidth=2 softtabstop=2 tabstop=2
'''

cs = '''
setlocal shiftwidth=4 softtabstop=4 tabstop=4
'''

terminal = '''
if has('nvim')
  startinsert 
else
  normal i
endif
'''
