[[plugins]]
repo = 'Shougo/dein.vim'
[[plugins]]
repo = 'wsdjeg/dein-ui.vim'
[[plugins]]
repo = 'haya14busa/dein-command.vim'

[[plugins]]
repo = 'chriskempson/base16-vim'

[[plugins]]
repo = 'whatyouhide/vim-gotham'

# coc {{{
[[plugins]]
repo = 'neoclide/coc.nvim'
depends = 'vim-snippets'
# on_i = 1
on_if = "matchstr(expand('%:p'),'jp.md') ==# ''"
merged = '0'
hook_add = 'source ~/.vim/rc/plugins/coc.rc.vim'

[[plugins]]
repo = 'honza/vim-snippets'

# [[plugins]]
# repo = 'SirVer/ultisnips'
# }}}

# Reference {{{
[[plugins]]
repo = 'vim-jp/vimdoc-ja'

[[plugins]]
repo = 'mojako/ref-sources.vim'
# hook_add = '''
# '''

[[plugins]]
repo = 'thinca/vim-ref'
depends = 'ref-sources.vim'
hook_add = '''
let g:ref_no_default_key_mappings = 1
let g:ref_man_lang = 'ja'
let g:ref_pydoc_cmd = 'python3 -m pydoc'
let g:ref_cache_dir = expand($CONFIG) . '/vim-ref/cache'
let g:ref_use_cache = 1
let g:ref_use_vimproc = 1
let g:ref_auto_resize = 1
let g:ref_wikipedia_lang = ['ja', 'en']
let g:ref_source_webdict_cmd = 'lynx -dump -nonumbers %s'
let g:ref_source_webdict_sites = {
\   'alc' : {
\     'url' : 'http://eow.alc.co.jp/%s/UTF-8/'
\   },
\   'je': {
\     'url': 'http://dictionary.infoseek.ne.jp/jeword/%s',
\   },
\   'ej': {
\     'url': 'http://dictionary.infoseek.ne.jp/ejword/%s',
\   }
\ }
let g:ref_source_webdict_sites.default = 'alc'
function! g:ref_source_webdict_sites.je.filter(output)
  return join(split(a:output, "\n")[15 :], "\n")
endfunction
function! g:ref_source_webdict_sites.ej.filter(output)
  return join(split(a:output, "\n")[15 :], "\n")
endfunction
function! g:ref_source_webdict_sites.alc.filter(output)
  return join(split(a:output, "\n")[42 :], "\n")
endfunction
noremap <expr> bs ':Ref webdict ej ' . expand('<cword>') . '<CR>'
noremap <expr> bS ':Ref webdict je ' . expand('<cword>') . '<CR>'
noremap <expr> ba ':Ref webdict alc ' . expand('<cword>') . '<CR>'
noremap <expr> bt ':Ref kotobankje ' . expand('<cword>') . '<CR>'
noremap <expr> bT ':Ref kotobank ' . expand('<cword>') . '<CR>'
noremap <expr> br ':Ref wikipedia_en ' . expand('<cword>') . '<CR>'
noremap <expr> bR ':Ref wikipedia_ja ' . expand('<cword>') . '<CR>'
'''
# }}}

# View {{{
[[plugins]]
repo = 'luochen1990/rainbow'
hook_add = 'let g:rainbow_active = 1'

[[plugins]]
repo = 'ryanoasis/vim-devicons'

[[plugins]]
repo = 'ap/vim-css-color'

[[plugins]]
repo = 'Yggdroot/indentLine'
[[plugins]]
repo = 'markonm/traces.vim'

# vista {{{
[[plugins]]
repo = 'liuchengxu/vista.vim'
hook_add = '''
let g:vista_icon_indent = ['╰─▸ ', '├─▸ ']
let g:vista_default_executive = 'coc'
let g:vista_fzf_preview = ['right:50%']
let g:vista#renderer#enable_icon = 1
let g:vista#renderer#icons = {
\ 'func':           "\Uff794",
\ 'function':       "\Uff794",
\ 'functions':      "\Uff794",
\ 'var':            "\Uff71b",
\ 'variable':       "\Uff71b",
\ 'variables':      "\Uff71b",
\ 'const':          "\Uff8ff",
\ 'constant':       "\Uff8ff",
\ 'method':         "\Uff6a6",
\ 'package':        "\Ufe612",
\ 'packages':       "\Ufe612",
\ 'enum':           "\Uff435",
\ 'enumerator':     "\Uff435",
\ 'module':         "\Uff668",
\ 'modules':        "\Uff668",
\ 'type':           "\Ufe22b",
\ 'typedef':        "\Ufe22b",
\ 'types':          "\Ufe22b",
\ 'field':          "\Uff93d",
\ 'fields':         "\Uff93d",
\ 'macro':          "\Uff8a3",
\ 'macros':         "\Uff8a3",
\ 'map':            "\Uffb44",
\ 'class':          "\Uff9a9",
\ 'augroup':        "\Uffb44",
\ 'struct':         "\Uffb44",
\ 'union':          "\Uffacd",
\ 'member':         "\Uff02b",
\ 'target':         "\Uff893",
\ 'property':       "\Uffab6",
\ 'interface':      "\Uffa52",
\ 'namespace':      "\Uff475",
\ 'subroutine':     "\Uff915",
\ 'implementation': "\Uff87a",
\ 'typeParameter':  "\Uff278",
\ 'default':        "\Uff29c"
\ }
'''

[[plugins]]
repo = 'Shougo/junkfile.vim'
on_source = 'denite.nvim'
hook_add = '''
'''
# }}}

# Lightline {{{
[[plugins]]
repo = 'itchyny/lightline.vim'
depends = ['vista', 'vim-devicons','lightline-ale']
hook_add = 'source ~/.vim/rc/plugins/lightline.rc.vim'

[[plugins]]
repo = 'maximbaz/lightline-ale'
# }}}
# }}}

# dependent {{{
# [[plugins]] */
# repo = 'nixprime/cpsm'
# build = 'sh -c "PY3=ON ./install.sh"'
[[plugins]]
repo = 'tyru/open-browser.vim'
[[plugins]]
repo = 'kana/vim-operator-user'
[[plugins]]
repo = 'kana/vim-textobj-user'
[[plugins]]
repo = 'vim-jp/vital.vim'
# }}}

# Editor_Configs {{{
[[plugins]]
repo ='sgur/vim-editorconfig'
[[plugins]]
repo = 'vim-scripts/autodate.vim'
[[plugins]]
repo = 'glidenote/memolist.vim'
hook_add = '''
let g:memolist_memo_suffix = "jp.md"
let g:memolist_path = "~/memo/"
let g:memolist_denite = 1
nmap <Leader>M [memo]
nnoremap [memo]n  :MemoNew<CR>
nnoremap [memo]l :MemoList<CR>
nnoremap [memo]g  :MemoGrep<CR>
let g:memolist_template_dir_path = "~/dotfiles/dots/vim/template/template_memo.md"
'''
# config }}}

# Fold/indent {{{
[[plugins]]
repo = 'thinca/vim-ft-help_fold'
[[plugins]]
repo = 'thinca/vim-ft-diff_fold'
[[plugins]]
repo = 'Konfekt/FastFold'
hook_add = '''
let g:fastfold_savehook = 1
let g:fastfold_fdmhook = 0
let g:fastfold_fold_movement_commands = [']m', '[m', 'mk']
let g:markdown_folding = 1
let g:tex_fold_enabled = 1
let g:vimsyn_folding = 'af'
let g:xml_syntax_folding = 1
let g:javaScript_fold = 1
let g:sh_fold_enabled= 7
let g:ruby_fold = 1
let g:perl_fold = 1
let g:perl_fold_blocks = 1
let g:r_syntax_folding = 1
let g:rust_fold = 1
let g:php_folding = 1
'''


# }}}

# uniqe{{{
# [[plugins]]
# repo = 'lambdalisue/gina.vim'
# hook_add = '''
# nnoremap <Right> :<C-u>Gina diff<CR>
# nnoremap <Left> :<C-u>Gina commit<CR>
# nnoremap <UP> :<C-u>Gina status<CR>
# nnoremap <Down> :<C-u>Gina push<CR>
# '''

[[plugins]]
repo = 'skanehira/gh.vim'

[[plugins]]
repo = 'junegunn/vim-easy-align'
hook_add = '''
xmap <CR> <Plug>(EasyAlign)
nmap <S-CR> <Plug>(EasyAlign)
'''
# }}}

# sub-mode {{{
[[plugins]]
repo = 'kana/vim-submode'
hook_add = '''
call submode#enter_with('bufmove', 'n', '', '<C-g>h', '<C-w>>')
call submode#enter_with('bufmove', 'n', '', '<C-g>i', '<C-w><')
call submode#enter_with('bufmove', 'n', '', '<C-g>n', '<C-w>+')
call submode#enter_with('bufmove', 'n', '', '<C-g>e', '<C-w>-')
call submode#enter_with('bufmove', 'n', '', '<C-g>H', '<C-w>H')
call submode#enter_with('bufmove', 'n', '', '<C-g>I', '<C-w>L')
call submode#enter_with('bufmove', 'n', '', '<C-g>N', '<C-w>J')
call submode#enter_with('bufmove', 'n', '', '<C-g>E', '<C-w>K')
call submode#enter_with('bufmove', 'n', '', '<C-g>O', '<C-w>r')
call submode#map('bufmove', 'n', '', 'h', '<C-w>>')
call submode#map('bufmove', 'n', '', 'i', '<C-w><')
call submode#map('bufmove', 'n', '', 'n', '<C-w>+')
call submode#map('bufmove', 'n', '', 'e', '<C-w>-')
call submode#map('bufmove', 'n', '', 'H', '<C-w>H')
call submode#map('bufmove', 'n', '', 'I', '<C-w>L')
call submode#map('bufmove', 'n', '', 'N', '<C-w>J')
call submode#map('bufmove', 'n', '', 'E', '<C-w>K')
call submode#map('bufmove', 'n', '', 'O', '<C-w>r')
call submode#enter_with('bufmove', 'n', '', '<C-g>y', ':call comfortable_motion#flick(g:comfortable_motion_impulse_multiplier * winheight(0) * 2)<CR>')
call submode#enter_with('bufmove', 'n', '', '<C-g>u', ':call comfortable_motion#flick(g:comfortable_motion_impulse_multiplier * winheight(0) * -2)<CR>')
call submode#enter_with('bufmove', 'n', '', '<C-g>Y', ':call comfortable_motion#flick(g:comfortable_motion_impulse_multiplier * winheight(0) * 4)<CR>')
call submode#enter_with('bufmove', 'n', '', '<C-g>U', ':call comfortable_motion#flick(g:comfortable_motion_impulse_multiplier * winheight(0) * -4)<CR>')
call submode#map('bufmove', 'n', '', 'y', ':call comfortable_motion#flick(g:comfortable_motion_impulse_multiplier * winheight(0) * 2)<CR>')
call submode#map('bufmove', 'n', '', 'u', ':call comfortable_motion#flick(g:comfortable_motion_impulse_multiplier * winheight(0) * -2)<CR>')
call submode#map('bufmove', 'n', '', 'U', ':call comfortable_motion#flick(g:comfortable_motion_impulse_multiplier * winheight(0) * 4)<CR>')
call submode#map('bufmove', 'n', '', 'Y', ':call comfortable_motion#flick(g:comfortable_motion_impulse_multiplier * winheight(0) * -4)<CR>')
'''
# }}}

# sandwitch {{{ 
[[plugins]]
repo = 'machakann/vim-sandwich'
hook_post_update = '''
let g:operator_sandwich_no_default_key_mappings = 1
let g:textobj_sandwich_no_default_key_mappings = 1
let g:sandwich_no_default_key_mappings = 1
let g:sandwich#recipes = deepcopy(g:sandwich#default_recipes)
let g:sandwich#recipes += [
\    {'buns': ['（', '）']},
\    {'buns': ['［', '］']},
\    {'buns': ['｛', '｝']},
\    {'buns': ['＜', '＞']},
\    {'buns': ['≪', '≫']},
\    {'buns': ['「', '」']},
\    {'buns': ['『', '』']},
\    {'buns': ['〈', '〉']},
\    {'buns': ['《', '》']},
\    {'buns': ['〔', '〕']},
\    {'buns': ['【', '】']},
\ ]
'''
hook_add = '''
nmap w <Nop>
xmap w <Nop>
omap w <Nop>
nmap W <Nop>
xmap W <Nop>
omap W <Nop>
nmap w  <Plug>(operator-sandwich-add)
nmap W  <Plug>(operator-sandwich-add)<Plug>(operator-sandwich-synchro-count)
map  Wd <Plug>operator-sandwich-delete<Plug>(textobj-sandwich-query-a)
map  wd <Plug>(operator-sandwich-delete)<Plug>(textobj-sandwich-auto-a)
map  Wr <Plug>(operator-sandwich-replace)<Plug>(textobj-sandwich-query-a)
map  wr <Plug>(operator-sandwich-replace)<Plug>(textobj-sandwich-auto-a)
map  mw <Plug>(operator-sandwich-delete)<Plug>(textobj-sandwich-auto-a)s
map  mW <Plug>(operator-sandwich-delete)<Plug>(textobj-sandwich-query-a)s
omap W  <Plug>(textobj-sandwich-query-i)
omap w  <Plug>(textobj-sandwich-auto-i)
omap sW <Plug>(textobj-sandwich-query-a)
omap sw <Plug>(textobj-sandwich-auto-a)
omap tW <Plug>(textobj-sandwich-query-a)
omap tw <Plug>(textobj-sandwich-auto-a)
xmap w <Plug>(operator-sandwich-add)
'''
# }}}

# smart_motion  {{{
[[plugins]]
repo = 'chaoren/vim-wordmotion'
hook_add = '''
let g:wordmotion_nomap = 1
map i <Plug>WordMotion_w
noremap <C-i> W
map h <Plug>WordMotion_b
noremap <C-h> B
map H <Plug>WordMotion_ge
map I <Plug>WordMotion_e
'''

[[plugins]]
repo = 'yuttie/comfortable-motion.vim'
hook_add = '''
let g:comfortable_motion_no_default_key_mappings = 1
noremap <silent> <ScrollWheelDown> :<c-u>call comfortable_motion#flick(40)<CR>
noremap <silent> <ScrollWheelUp>   :<c-u>call comfortable_motion#flick(-40)<CR>
'''
[[plugins]]
repo = 'arthurxavierx/vim-unicoder'
# }}}

# action {{{
# emment {{{
[[plugins]]
repo = 'mattn/emmet-vim'
hook_add = '''
let g:user_emmet_install_global = 1
let g:user_emmet_mode='vin'
" let g:user_emmet_leader_key='<C-;>'
imap   <C-;>;   <plug>(emmet-expand-abbr)
imap   <C-;>.   <plug>(emmet-expand-word)
" imap   <C-;>u   <plug>(emmet-update-tag)
" imap   <C-;>d   <plug>(emmet-balance-tag-inward)
" imap   <C-;>D   <plug>(emmet-balance-tag-outward)
" imap   <C-;>n   <plug>(emmet-move-next)
" imap   <C-;>N   <plug>(emmet-move-prev)
" imap   <C-;>i   <plug>(emmet-image-size)
" imap   <C-;>/   <plug>(emmet-toggle-comment)
" imap   <C-;>j   <plug>(emmet-split-join-tag)
" imap   <C-;>k   <plug>(emmet-remove-tag)
" imap   <C-;>a   <plug>(emmet-anchorize-url)
" imap   <C-;>A   <plug>(emmet-anchorize-summary)
" imap   <C-;>m   <plug>(emmet-merge-lines)
" imap   <C-;>c   <plug>(emmet-code-pretty)
" let g:user_emmet_expandabbr_key = '<<C-,>>,'
" let g:user_emmet_expandword_key = '<<C-.>>;'
" let g:user_emmet_update_tag = '<<C-.>>u'
" let g:user_emmet_balancetaginward_key = '<<C-.>>d'
" let g:user_emmet_balancetagoutward_key = '<<C-.>>D'
" let g:user_emmet_next_key = '<<C-.>>n'
" let g:user_emmet_prev_key = '<<C-.>>N'
" let g:user_emmet_imagesize_key = '<<C-.>>i'
" let g:user_emmet_togglecomment_key = '<<C-.>>/'
" let g:user_emmet_splitjointag_key = '<<C-.>>j'
" let g:user_emmet_removetag_key = '<<C-.>>k'
" let g:user_emmet_anchorizeurl_key = '<<C-.>>a'
" let g:user_emmet_anchorizesummary_key = '<<C-.>>A'
" let g:user_emmet_mergelines_key = '<<C-.>>m'
" let g:user_emmet_codepretty_key = '<<C-.>>c'
'''
[[plugins]]
repo = 'pbrisbin/vim-mkdir'

[[plugins]]
repo = 'junegunn/fzf'
# }}}
# command }}}

# nvim_setting {{{
[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'
on_if = '!has("nvim")'

[[plugins]]
repo = 'roxma/nvim-yarp'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'osyo-manga/vital-migemo'
# }}}

# FileType{{{
[[plugins]]
repo = 'Shirk/vim-gas'

[[plugins]]
repo = 'mmikeww/autohotkey.vim'

[[plugins]]
repo = 'vim-jp/autofmt'

[[plugins]]
repo = 'vim-jp/syntax-vim-ex'

[[plugins]]
repo = 'othree/javascript-libraries-syntax.vim'

[[plugins]]
repo = 'othree/es.next.syntax.vim'

[[plugins]]
repo = 'cespare/vim-toml'
# }}}

# Unused {{{
# [[plugins]]
# repo = 'wakatime/vim-wakatime'
# hook_source = '''
# let g:wakatime_PythonBinary = g:python3_host_prog
# '''

# [[plugins]]
# repo = 'azadkuh/vim-cmus'

# [[plugins]]
# repo = 'sheerun/vim-polyglot'
# hook_add = '''
# let g:polyglot_disabled = ['markdown', 'tsx', 'typescript', 'csv', 'cpp']
# let g:loaded_sleuth = 1
# '''

# [[plugins]]
# repo = 'thinca/vim-qfreplace'
# on_ft = ['qf']
# [plugins.ftplugin]
# qf = '''
#   nnoremap <buffer> r :<C-u>Qfreplace<CR>
# '''

# }}}

# vim: ts=2 et sw=2 fdm=marker
