[[plugins]]
repo = 'Shougo/dein.vim'

# coc {{{
[[plugins]]
repo = 'neoclide/coc.nvim'
rev = 'release'
on_if = "matchstr(expand('%:p'),'jp.md') ==# ''"
merged = '0'
hook_add = 'source ~/.vim/rc/plugins/coc.rc.vim'

[[plugins]]
repo = 'honza/vim-snippets'

# filetype {{{
[[plugins]]
repo = 'sheerun/vim-polyglot'
hook_add = '''
let g:polyglot_disabled = ['markdown', 'tsx', 'typescript', 'csv', 'cpp']
let g:loaded_sleuth = 1
'''
[[plugins]]
repo = 'romainl/vim-devdocs'

[[plugins]]
repo = 'mmikeww/autohotkey.vim'
# }}}
# vim-ref {{{
[[plugins]]
repo = 'mojako/ref-sources.vim'
[[plugins]]
repo = 'terlar/vim-ref-fish'
on_ft = 'fish'
hook_add = '''
setlocal keywordprg=:Ref\ fish
'''
[[plugins]]
repo = 'thinca/vim-ref'
depends = 'ref-sources.vim'
hook_add = '''
let g:ref_no_default_key_mappings = 1
let g:ref_man_lang = 'ja'
let g:ref_pydoc_cmd = 'python3 -m pydoc'
let g:ref_cache_dir = $HOME . '/.vim/vim-ref/cache'
let g:ref_use_cache           = 1
let g:ref_use_vimproc         = 1
let g:ref_wikipedia_lang = ['ja', 'en']
let g:ref_source_webdict_sites = {
\   'alc' : {
\     'url' : 'http://eow.alc.co.jp/%s/UTF-8/'
\   },
\   'je': {
\     'url': 'http://dictionary.infoseek.ne.jp/jeword/%s',
\   },
\   'ej': {
\     'url': 'http://dictionary.infoseek.ne.jp/ejword/%s',
\   }
\ }
let g:ref_source_webdict_sites.default = 'alc'
function! g:ref_source_webdict_sites.je.filter(output)
  return join(split(a:output, "\n")[15 :], "\n")
endfunction
function! g:ref_source_webdict_sites.ej.filter(output)
  return join(split(a:output, "\n")[15 :], "\n")
endfunction
function! g:ref_source_webdict_sites.alc.filter(output)
  return join(split(a:output, "\n")[42 :], "\n")
endfunction
nmap bb <Plug>(ref-keyword)
noremap <expr> bs ':Ref webdict ej ' . expand('<cword>') . '<CR>'
noremap <expr> bS ':Ref webdict je ' . expand('<cword>') . '<CR>'
noremap <expr> ba ':Ref webdict alc ' . expand('<cword>') . '<CR>'
noremap <expr> bt ':Ref kotobankje ' . expand('<cword>') . '<CR>'
noremap <expr> bT ':Ref kotobank ' . expand('<cword>') . '<CR>'
noremap <expr> br ':Ref wikipedia_en ' . expand('<cword>') . '<CR>'
noremap <expr> bR ':Ref wikipedia ' . expand('<cword>') . '<CR>'
'''
[[plugins]]
repo = 'ryanoasis/vim-devicons'
# }}}
# View {{{
[[plugins]]
repo = 'luochen1990/rainbow'
hook_add = 'let g:rainbow_active = 1'

[[plugins]]
repo = 'ap/vim-css-color'
# Lightline {{{
[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = 'source ~/.vim/rc/plugins/lightline.rc.vim'
depends = ['vista', 'vim-devicons','lightline-ale']
# }}}

[[plugins]]
repo = 'maximbaz/lightline-ale'
[[plugins]]
repo = 'Yggdroot/indentLine'
[[plugins]]
repo = 'markonm/traces.vim'
[[plugins]]
repo = 'wakatime/vim-wakatime'
# hook_source = '''
# let g:wakatime_PythonBinary = g:python3_host_prog
# '''
# }}}
# dependent {{{
[[plugins]]
repo = 'nixprime/cpsm'
build = 'sh -c "PY3=ON ./install.sh"'
[[plugins]]
repo = 'tyru/open-browser.vim'
[[plugins]]
repo = 'kana/vim-operator-user'
[[plugins]]
repo = 'kana/vim-textobj-user'
# }}}
# Configs {{{
[[plugins]]
repo ='editorconfig/editorconfig-vim'
[[plugins]]
repo = 'vim-scripts/autodate.vim'
[[plugins]]
repo = 'thinca/vim-ft-help_fold'
[[plugins]]
repo = 'thinca/vim-ft-diff_fold'
[[plugins]]
repo = 'Konfekt/FastFold'
hook_add = '''
let g:fastfold_savehook = 1
let g:fastfold_fdmhook = 0
let g:fastfold_fold_movement_commands = [']m', '[m', 'mk']
let g:markdown_folding = 1
let g:tex_fold_enabled = 1
let g:vimsyn_folding = 'af'
let g:xml_syntax_folding = 1
let g:javaScript_fold = 1
let g:sh_fold_enabled= 7
let g:ruby_fold = 1
let g:perl_fold = 1
let g:perl_fold_blocks = 1
let g:r_syntax_folding = 1
let g:rust_fold = 1
let g:php_folding = 1

xnoremap sm :<c-u>FastFoldUpdate<cr><esc>:<c-u>normal! ]zv[z<cr>
xnoremap tm :<c-u>FastFoldUpdate<cr><esc>:<c-u>normal! ]zV[z<cr>
'''
[[plugin]]
repo = 'skanehira/gh.vim'
# config }}}

[[plugins]]
repo = 'jacquesbh/vim-showmarks'
hook_add = '''
nnoremap <C-m> :<c-u>ShowMarksOnce<cr>
'''
# [[plugins]]
# repo = 'lambdalisue/gina.vim'
# hook_add = '''
# nnoremap <Right> :<C-u>Gina diff<CR>
# nnoremap <Left> :<C-u>Gina commit<CR>
# nnoremap <UP> :<C-u>Gina status<CR>
# nnoremap <Down> :<C-u>Gina push<CR>
# '''
[[plugins]]
repo = 'junegunn/vim-easy-align'
hook_add = '''
xmap <CR> <Plug>(EasyAlign)
nmap mg <Plug>(EasyAlign)
'''

[[plugins]]
repo = 'cohama/lexima.vim'

[[plugins]]
repo = 'yuttie/comfortable-motion.vim'
hook_add = '''
let g:comfortable_motion_no_default_key_mappings = 1
noremap <silent> <ScrollWheelDown> :<c-u>call comfortable_motion#flick(40)<CR>
noremap <silent> <ScrollWheelUp>   :<c-u>call comfortable_motion#flick(-40)<CR>
'''
[[plugins]]
repo = 'arthurxavierx/vim-unicoder'

# sandwitch {{{
[[plugins]]
repo = 'machakann/vim-sandwich'
hook_post_update = '''
let g:sandwich#recipes = deepcopy(g:sandwich#default_recipes)
let g:sandwich#recipes += [
\    {'buns': ['（', '）']},
\    {'buns': ['［', '］']},
\    {'buns': ['｛', '｝']},
\    {'buns': ['＜', '＞']},
\    {'buns': ['≪', '≫']},
\    {'buns': ['「', '」']},
\    {'buns': ['『', '』']},
\    {'buns': ['〈', '〉']},
\    {'buns': ['《', '》']},
\    {'buns': ['〔', '〕']},
\    {'buns': ['【', '】']},
\ ]
'''
hook_add = '''
let g:operator_sandwich_no_default_key_mappings = 1
let g:textobj_sandwich_no_default_key_mappings = 1
let g:sandwich_no_default_key_mappings = 1
" nmap w <Nop>
" xmap w <Nop>
" omap w <Nop>
" nmap W <Nop>
" xmap W <Nop>
" omap W <Nop>
nmap w  <Plug>(operator-sandwich-add)
nmap W  <Plug>(operator-sandwich-add)<Plug>(operator-sandwich-synchro-count)
map  Wd <Plug>(operator-sandwich-delete)<Plug>(textobj-sandwich-query-a)
map  wd <Plug>(operator-sandwich-delete)<Plug>(textobj-sandwich-auto-a)
map  Wr <Plug>(operator-sandwich-replace)<Plug>(textobj-sandwich-query-a)
map  wr <Plug>(operator-sandwich-replace)<Plug>(textobj-sandwich-auto-a)
map  mw <Plug>(operator-sandwich-delete)<Plug>(textobj-sandwich-auto-a)s
map  mW <Plug>(operator-sandwich-delete)<Plug>(textobj-sandwich-query-a)s
omap W  <Plug>(textobj-sandwich-query-i)
omap w  <Plug>(textobj-sandwich-auto-i)
omap sW <Plug>(textobj-sandwich-query-i)
omap sw <Plug>(textobj-sandwich-auto-i)
omap tW <Plug>(textobj-sandwich-query-a)
omap tw <Plug>(textobj-sandwich-query-a)
xmap w  <Plug>(textobj-sandwich-auto-i)
xmap W  <Plug>(textobj-sandwich-query-i)
xmap sW <Plug>(textobj-sandwich-query-i)
xmap sw <Plug>(textobj-sandwich-auto-i)
xmap tW <Plug>(textobj-sandwich-query-a)
xmap tw <Plug>(textobj-sandwich-query-a)
'''
# }}}
# action {{{
# emment {{{
[[plugins]]
repo = 'mattn/emmet-vim'
hook_add = '''
let g:user_emmet_install_global = 1
let g:user_emmet_mode='vn'
let g:user_emmet_leader_key='<C-.>'
'''
[[plugins]]
repo = 'pbrisbin/vim-mkdir'
[[plugins]]
repo = 'junegunn/fzf'
[[plugins]]
repo = 'previm/previm'
[[plugins]]
repo = 'azadkuh/vim-cmus'
# }}}
# command }}}
# nvim_setting {{{
[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'
on_if = '!has("nvim")'

[[plugins]]
repo = 'roxma/nvim-yarp'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'osyo-manga/vital-migemo'
# }}}

# vim: ts=2 et sw=2 fdm=marker
